---
- name: Delete the Loom server.
  hosts: localhost
  connection: local
  tasks:
  - name: Delete the Loom server.
    local_action:
      module: gce
      state: 'absent'
      instance_names: "{{lookup('env','SERVER_NAME')}}"
