---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    server_name: "{{lookup('env','SERVER_NAME')}}"
    server_zone: "{{lookup('env','SERVER_ZONE')}}"
    server_vm_image: "{{lookup('env','SERVER_VM_IMAGE')}}"
    server_instance_type: "{{lookup('env','SERVER_INSTANCE_TYPE')}}"
    server_network: "{{lookup('env','SERVER_NETWORK')}}"
    server_tags: "{{lookup('env','SERVER_TAGS')}}"
    server_disk_type: "{{lookup('env','SERVER_DISK_TYPE')}}"
    server_disk_size: "{{lookup('env','SERVER_DISK_SIZE')}}"
    use_internal_ip: "{{lookup('env','CLIENT_USES_SERVER_INTERNAL_IP')}}"
  tasks:
  - name: Create a boot disk with the same name as the server instance.
    gce_pd: name={{server_name}} image={{server_vm_image}} disk_type={{server_disk_type}} size_gb={{server_disk_size}} zone={{server_zone}} mode=READ_WRITE
  - name: Boot up a new instance using the just-created boot disk.
    gce: name={{server_name}} disks={{server_name}} zone={{server_zone}} machine_type={{server_instance_type}} network={{server_network}} service_account_permissions=cloud-platform tags={{server_tags|default(omit)}}
    register: gce_result
  - name: Wait for SSH port to be available.
    wait_for: host={{ (use_internal_ip) | ternary(item.private_ip, item.public_ip) }} port=22 delay=10 timeout=300 search_regex=OpenSSH
    with_items: '{{ gce_result.instance_data }}'
  - name: Add host to new_instances.
    add_host: hostname={{ (use_internal_ip) | ternary(item.private_ip, item.public_ip) }} groupname=new_instances
    with_items: '{{ gce_result.instance_data }}'

- name: Set up the Loom server on the new instance. 
  hosts: new_instances
  become: yes
  roles:
  - docker
  - loom_master

- name: Run the user-provided playbook.
  include: "{{lookup('env','RUN_AFTER_SERVER_CREATE_PLAYBOOK_PATH')}}"
