---
- name: Create a new instance for the Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a boot disk with the same name as the worker instance.
    gce_pd: name={{node_name}} image={{image}} disk_type={{boot_disk_type}} size_gb={{boot_disk_size_gb}} zone={{zone}} mode=READ_WRITE
  - name: Boot up a new instance using the just-created boot disk.
    gce: name={{node_name}} disks={{node_name}} zone={{zone}} machine_type={{instance_type}} network={{worker_network}} service_account_permissions=cloud-platform tags={{worker_tags|default(omit)}} 
    register: gce_result
  - name: Create a scratch disk and attach it to the worker instance.
    gce_pd: instance_name={{node_name}} name={{scratch_disk_name}} disk_type={{scratch_disk_type}} size_gb={{scratch_disk_size_gb}} zone={{zone}} mode=READ_WRITE
  - name: Wait for SSH to come up.
    wait_for: host={{ item.private_ip }} port=22 delay=10 timeout=300 search_regex=OpenSSH
    with_items: '{{ gce_result.instance_data }}'
  - name: Add host to groupname.
    add_host: hostname={{ item.private_ip }} groupname=new_instances
    with_items: '{{ gce_result.instance_data }}'

- name: Set up new instance(s).
  hosts: new_instances
  remote_user: loom
  become_method: sudo
  become: yes
  tasks:
  - name: Create a filesystem on the scratch disk.
    filesystem: fstype=ext4 dev={{scratch_disk_device_path}} force=no
  - name: Create the scratch disk mount point.
    file: path={{scratch_disk_mount_point}} state=directory
  - name: Mount the scratch disk at the mount point.
    mount: name={{scratch_disk_mount_point}} fstype=ext4 src={{scratch_disk_device_path}} state=mounted
  - name: Pull Loom Docker image.
    docker_image: name={{docker_full_name}} tag={{docker_tag}} api_version=auto
  - name: Pull task run Docker image.
    docker_image: name={{task_run_docker_image}} api_version=auto

#- name: Remove worker external IP. 
#  hosts: localhost
#  connection: local
#  gather_facts: no
#  tasks:
#  - name: Remove worker external IP.
#    shell: gcloud compute instances delete-access-config {{node_name}} --access-config-name "External NAT" --zone {{zone}}
